package btsemm

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"sort"
	"strings"
	"sync"
	"time"
)

// TrackedOrder represents a bot-managed order with local state.
type TrackedOrder struct {
	ClOrderID string
	OrderID   string
	Symbol    string
	Side      OrderSide
	Price     float64
	Size      float64
	Status    OrderStatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

// IsOpen returns true if the order is in an active state.
func (o *TrackedOrder) IsOpen() bool {
	return o.Status == OrderStatusInserted || o.Status == OrderStatusPartiallyFilled
}

// OrderManager tracks all orders placed by this bot instance.
type OrderManager struct {
	mu     sync.RWMutex
	orders map[string]*TrackedOrder // keyed by ClOrderID
	client *Client
	symbol string
	prefix string // unique per bot instance
	seq    int64

	// Verbose enables verbose-gated debug logs (currently only at the end of
	// Reconcile). Set by the engine from EngineConfig.Verbose.
	Verbose bool

	// lastPlaceTime is the time of the most recent successful Place() call.
	// Used by the watchdog to surface "no orders placed in N minutes".
	lastPlaceMu   sync.Mutex
	lastPlaceTime time.Time
}

// NewOrderManager creates an order manager for the given symbol.
// Each instance gets a random prefix so multiple bots never collide.
func NewOrderManager(client *Client, symbol string) *OrderManager {
	b := make([]byte, 3)
	rand.Read(b)
	prefix := "mm" + hex.EncodeToString(b) + "-"

	return &OrderManager{
		orders: make(map[string]*TrackedOrder),
		client: client,
		symbol: symbol,
		prefix: prefix,
	}
}

// Prefix returns this bot instance's order prefix.
func (om *OrderManager) Prefix() string {
	return om.prefix
}

// genClOrderID generates a unique client order ID with this instance's prefix.
func (om *OrderManager) genClOrderID() string {
	om.seq++
	return fmt.Sprintf("%s%d-%d", om.prefix, time.Now().UnixMilli(), om.seq)
}

// IsOurs returns true if the given clOrderID was generated by this bot instance.
func (om *OrderManager) IsOurs(clOrderID string) bool {
	return strings.HasPrefix(clOrderID, om.prefix)
}

// Place creates a new order and tracks it locally.
func (om *OrderManager) Place(side OrderSide, price, size float64, postOnly bool) (*TrackedOrder, error) {
	clID := om.genClOrderID()
	req := &CreateOrderRequest{
		Symbol:    om.symbol,
		Side:      side,
		Type:      OrderTypeLimit,
		Price:     price,
		Size:      size,
		PostOnly:  postOnly,
		ClOrderID: clID,
		TxType:    "LIMIT",
	}

	orders, err := om.client.CreateOrder(req)
	if err != nil {
		return nil, fmt.Errorf("btse: place order: %w", err)
	}

	now := time.Now()
	tracked := &TrackedOrder{
		ClOrderID: clID,
		Symbol:    om.symbol,
		Side:      side,
		Price:     price,
		Size:      size,
		Status:    OrderStatusInserted,
		CreatedAt: now,
		UpdatedAt: now,
	}

	if len(orders) > 0 {
		tracked.OrderID = orders[0].OrderID
		tracked.Status = orders[0].Status
	}

	om.mu.Lock()
	om.orders[clID] = tracked
	om.mu.Unlock()

	om.lastPlaceMu.Lock()
	om.lastPlaceTime = now
	om.lastPlaceMu.Unlock()

	return tracked, nil
}

// LastPlaceTime returns the time of the most recent successful Place() call,
// or the zero time if no order has been placed yet.
func (om *OrderManager) LastPlaceTime() time.Time {
	om.lastPlaceMu.Lock()
	defer om.lastPlaceMu.Unlock()
	return om.lastPlaceTime
}

// OrderCounts returns the number of open BUY, SELL, and total tracked orders
// in a single pass without allocating an intermediate slice.
func (om *OrderManager) OrderCounts() (buys, sells, total int) {
	om.mu.RLock()
	defer om.mu.RUnlock()
	for _, o := range om.orders {
		if !o.IsOpen() {
			continue
		}
		total++
		if o.Side == SideBuy {
			buys++
		} else {
			sells++
		}
	}
	return
}

// DumpOrders writes a sorted listing of all currently open tracked orders to
// the given writer. BUYs are printed first (ascending price), then SELLs
// (ascending price). Each line includes side, price, size, status, age, and
// client order ID.
func (om *OrderManager) DumpOrders(w io.Writer) {
	open := om.OpenOrders() // already returns copies under RLock
	sort.Slice(open, func(i, j int) bool {
		if open[i].Side != open[j].Side {
			return open[i].Side == SideBuy
		}
		return open[i].Price < open[j].Price
	})
	for _, o := range open {
		age := time.Since(o.CreatedAt).Truncate(time.Second)
		fmt.Fprintf(w, "  %-4s %12.6f  %12.6f  status=%-2d age=%-10s %s\n",
			o.Side, o.Price, o.Size, o.Status, age, o.ClOrderID)
	}
}

// Amend modifies an existing order by cancelling and replacing it.
// BTSE spot amend API is unreliable for small price changes, so we use cancel+replace.
func (om *OrderManager) Amend(clOrderID string, price, size float64) (*TrackedOrder, error) {
	om.mu.RLock()
	tracked, ok := om.orders[clOrderID]
	om.mu.RUnlock()
	if !ok {
		return nil, fmt.Errorf("btse: order %s not tracked", clOrderID)
	}

	om.Cancel(clOrderID)
	return om.Place(tracked.Side, price, size, true)
}

// Cancel cancels a tracked order.
func (om *OrderManager) Cancel(clOrderID string) error {
	om.mu.RLock()
	_, ok := om.orders[clOrderID]
	om.mu.RUnlock()
	if !ok {
		return fmt.Errorf("btse: order %s not tracked", clOrderID)
	}

	_, err := om.client.CancelOrder(&CancelOrderRequest{
		Symbol:    om.symbol,
		ClOrderID: clOrderID,
	})

	// Mark as cancelled regardless of error — if the exchange says 404 (not found),
	// the order is already gone. Don't leave ghost orders in local state.
	om.mu.Lock()
	if t, ok := om.orders[clOrderID]; ok {
		t.Status = OrderStatusCancelled
		t.UpdatedAt = time.Now()
	}
	om.mu.Unlock()

	if err != nil {
		// 404 = order already gone on exchange, not a real error
		if apiErr, ok := err.(*APIError); ok && apiErr.StatusCode == 404 {
			return nil
		}
		return fmt.Errorf("btse: cancel order: %w", err)
	}

	return nil
}

// CancelAll cancels all open tracked orders.
func (om *OrderManager) CancelAll() error {
	om.mu.RLock()
	var toCancel []string
	for clID, o := range om.orders {
		if o.IsOpen() {
			toCancel = append(toCancel, clID)
		}
	}
	om.mu.RUnlock()

	var lastErr error
	for _, clID := range toCancel {
		if err := om.Cancel(clID); err != nil {
			lastErr = err
		}
	}
	return lastErr
}

// OpenOrders returns a copy of all currently open tracked orders.
func (om *OrderManager) OpenOrders() []*TrackedOrder {
	om.mu.RLock()
	defer om.mu.RUnlock()
	var result []*TrackedOrder
	for _, o := range om.orders {
		if o.IsOpen() {
			cp := *o
			result = append(result, &cp)
		}
	}
	return result
}

// ProcessNotification updates local order state from a WebSocket notification.
func (om *OrderManager) ProcessNotification(n WSOrderNotification) {
	if !om.IsOurs(n.ClOrderID) {
		return
	}

	om.mu.Lock()
	defer om.mu.Unlock()

	tracked, ok := om.orders[n.ClOrderID]
	if !ok {
		return
	}

	tracked.Status = n.Status
	tracked.UpdatedAt = time.Now()
	if n.OrderID != "" {
		tracked.OrderID = n.OrderID
	}
}

// Reconcile polls open orders from the exchange and fixes drift between
// local state and the exchange.
func (om *OrderManager) Reconcile() error {
	exchangeOrders, err := om.client.GetOpenOrders(om.symbol)
	if err != nil {
		return fmt.Errorf("btse: reconcile: %w", err)
	}

	// Build set of exchange order IDs
	exchangeSet := make(map[string]Order, len(exchangeOrders))
	for _, o := range exchangeOrders {
		if o.ClOrderID != "" {
			exchangeSet[o.ClOrderID] = o
		}
	}

	om.mu.Lock()
	// Track diff for verbose logging.
	var localOpen, removed, added int
	now := time.Now()

	// Mark locally-open orders that are gone from exchange as cancelled
	for clID, tracked := range om.orders {
		if !tracked.IsOpen() {
			continue
		}
		localOpen++
		if _, exists := exchangeSet[clID]; !exists {
			tracked.Status = OrderStatusCancelled
			tracked.UpdatedAt = now
			removed++
		}
	}

	// Add exchange orders that we own but don't have locally
	for clID, o := range exchangeSet {
		if !om.IsOurs(clID) {
			continue
		}
		if _, exists := om.orders[clID]; !exists {
			om.orders[clID] = &TrackedOrder{
				ClOrderID: clID,
				OrderID:   o.OrderID,
				Symbol:    o.Symbol,
				Side:      OrderSide(o.Side),
				Price:     o.Price,
				Size:      o.RemainingOrderBaseSize,
				Status:    o.Status,
				CreatedAt: time.UnixMilli(o.Timestamp),
				UpdatedAt: now,
			}
			added++
		}
	}
	om.mu.Unlock()

	if om.Verbose {
		log.Printf("orders: reconcile: exchange=%d local_open=%d (added=%d removed=%d)",
			len(exchangeSet), localOpen, added, removed)
	}

	return nil
}

// Cleanup removes terminal (non-open) orders older than the given duration.
func (om *OrderManager) Cleanup(maxAge time.Duration) {
	cutoff := time.Now().Add(-maxAge)
	om.mu.Lock()
	defer om.mu.Unlock()
	for clID, o := range om.orders {
		if !o.IsOpen() && o.UpdatedAt.Before(cutoff) {
			delete(om.orders, clID)
		}
	}
}
